package com.robsartin.setlistscout.migration;

import com.robsartin.setlistscout.catalog.ArtistNameNormalizer;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Issue #141: production's {@code artist} table carries an ORPHANED single-column
 * {@code UNIQUE (name)} constraint, a leftover from before multi-tenancy (#27) with a
 * Hibernate-generated hash name (e.g. {@code ukr03a96lqhsb7djq2tn4rq60vn} -- environment-specific,
 * never written in any migration). {@code V1__baseline.sql}'s {@code CREATE TABLE IF NOT EXISTS} is
 * a no-op against that already-existing table, and {@code V2__reconcile_owner_columns.sql}'s
 * retrofit only looks for a constraint literally named {@code artist_owner_name_key}, so neither
 * one ever found or dropped it. Because {@code ArtistRepository.insertIfAbsent}'s
 * {@code ON CONFLICT (owner, name) DO NOTHING} only suppresses conflicts on the constraint it
 * names, a violation of this OTHER, still-present constraint keeps throwing -- hit repeatedly in
 * production whenever two different owners add an artist with the same name, a case the composite
 * {@code (owner, name)} constraint is supposed to allow.
 *
 * <p>This test always migrates through to latest, so it also sees every later change to
 * {@code artist}'s constraints -- including #219's V27, which drops {@code artist_owner_name_key}
 * itself as redundant with the stronger {@code artist_owner_normalized_name_key} (V21, #179). The
 * assertions below were updated accordingly: they now check the surviving normalized constraint
 * rather than the composite one this test originally pinned, and step 5's last case (a hand-written
 * row with a {@code normalized_name} inconsistent with its own {@code name}) now succeeds instead
 * of throwing, since #219 is precisely what stopped catching that shape. See
 * {@code DropArtistOwnerNameConstraintMigrationTest} for the dedicated schema assertion.
 *
 * <p>Builds a genuine pre-#27 legacy {@code artist} shape (no {@code owner} column, like
 * {@link LegacyOwnerColumnMigrationTest}) but ALSO carrying a hash-named single-column
 * {@code UNIQUE (name)} constraint -- exactly what a real single-tenant-era table would have had.
 * Migrates through V1 (no-op on the already-existing table), V2 (retrofits {@code owner}, adds the
 * composite constraint since it's absent), up through the new migration, then asserts: the orphaned
 * constraint is gone, the composite constraint is still enforced (same owner + same name twice is
 * still rejected), and two DIFFERENT owners can now share a name without error. Runs in CI (needs
 * Docker). Without the new migration this fails: the cross-owner insert throws, reproducing the
 * exact production bug.
 */
@Testcontainers
class DropOrphanedArtistNameConstraintMigrationTest {

    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    // artist as it existed pre-#27: no `owner` column, plus a hash-named orphaned single-column
    // unique constraint -- the shape Hibernate's old ddl-auto=update would have created for a
    // single-tenant `name` uniqueness rule. Deliberately a DIFFERENT-looking hash than the real
    // prod name, to prove the migration finds it by column signature, not a hardcoded/guessed name.
    private static final String ORPHANED_CONSTRAINT_NAME = "uk9f8e7d6c5b4a3f2e1d0c";
    private static final String LEGACY_SCHEMA = """
            CREATE TABLE artist (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(255) NOT NULL,
                source varchar(255) NOT NULL,
                status varchar(255) NOT NULL,
                created_at timestamp(6) with time zone NOT NULL,
                CONSTRAINT %s UNIQUE (name)
            );
            """.formatted(ORPHANED_CONSTRAINT_NAME);

    @Test
    void dropsOrphanedSingleColumnConstraintButKeepsCompositeEnforced() throws Exception {
        // 1. Stand up the legacy pre-owner artist table, already carrying the orphaned constraint,
        // with a pre-existing row (mirrors a real single-tenant-era production row).
        try (Connection c = postgres.createConnection(""); Statement s = c.createStatement()) {
            s.execute(LEGACY_SCHEMA);
            s.execute("INSERT INTO artist (name, source, status, created_at) "
                    + "VALUES ('Nebraska', 'SEED_LIST', 'SEED', now())");
        }

        // 2. Confirm the fixture is real: a second row with the same name is rejected by the
        // orphaned constraint pre-migration -- the actual failure mode being reproduced.
        try (Connection c = postgres.createConnection(""); Statement s = c.createStatement()) {
            assertThatThrownBy(() -> s.execute("INSERT INTO artist (name, source, status, created_at) "
                    + "VALUES ('Nebraska', 'SEED_LIST', 'SEED', now())"))
                    .isInstanceOf(SQLException.class)
                    .hasMessageContaining(ORPHANED_CONSTRAINT_NAME);
        }

        // 3. Adopt Flyway with the app's real settings and migrate to latest: V1 no-ops (artist
        // already exists), V2 retrofits `owner` + adds the composite constraint (absent), then the
        // new migration drops the orphaned one.
        MigrateResult result = Flyway.configure()
                .dataSource(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .locations("classpath:db/migration")
                .load()
                .migrate();
        assertThat(result.success).isTrue();

        try (Connection c = postgres.createConnection(""); Statement s = c.createStatement()) {
            // 4. The orphaned single-column constraint is gone by name...
            assertThat(constraintExists(s, ORPHANED_CONSTRAINT_NAME))
                    .as("orphaned single-column constraint dropped").isFalse();
            // ...and no OTHER unique constraint on just {name} was left behind or created instead.
            assertThat(uniqueConstraintColumnSets(s)).as("no unique constraint left on just {name}")
                    .doesNotContain("name");

            // 5. artist_owner_name_key itself is dropped later, as redundant (#219) -- this test
            // migrates through the FULL chain, so what remains here is the stronger
            // artist_owner_normalized_name_key, and IT is what still rejects a same-owner
            // same-name duplicate. No unique constraint on just {name} was left behind either way
            // (asserted above), which is the actual claim V15/#141 makes.
            assertThat(constraintExists(s, "artist_owner_name_key"))
                    .as("artist_owner_name_key -- dropped later as redundant, see #219").isFalse();
            assertThat(uniqueConstraintColumnSets(s))
                    .as("only the normalized (owner, normalized_name) constraint remains -- #219")
                    .containsExactly("normalized_name,owner");

            String wilburysNormalizedName = ArtistNameNormalizer.normalize("Traveling Wilburys");
            s.execute("INSERT INTO artist (owner, name, normalized_name, source, status, created_at) "
                    + "VALUES ('rob@example.com', 'Traveling Wilburys', '" + wilburysNormalizedName
                    + "', 'SEED_LIST', 'SEED', now())");
            assertThatThrownBy(() -> s.execute(
                    "INSERT INTO artist (owner, name, normalized_name, source, status, created_at) "
                            + "VALUES ('rob@example.com', 'Traveling Wilburys', '" + wilburysNormalizedName
                            + "', 'SEED_LIST', 'SEED', now())"))
                    .as("same owner + same name is still rejected, now via the normalized arbiter alone")
                    .isInstanceOf(SQLException.class)
                    .hasMessageContaining("artist_owner_normalized_name_key");

            // #219: this next row is the one shape ONLY the now-dropped artist_owner_name_key ever
            // caught -- same owner and name, but a normalized_name that is NOT the normalizer's
            // output for it. Through V22 that made it worth keeping (see the pre-#219
            // ArtistRepository#insertIfAbsent javadoc); #219 found that reasoning falsified by a CI
            // failure under real concurrency and dropped the constraint as redundant. This row now
            // inserts cleanly -- deliberately pinned here rather than left as an unnoticed
            // behaviour change, and safe because no live write path can ever produce a
            // normalized_name inconsistent with its own name (see
            // DropArtistOwnerNameConstraintMigrationTest).
            assertThatCode(() -> s.execute(
                    "INSERT INTO artist (owner, name, normalized_name, source, status, created_at) "
                            + "VALUES ('rob@example.com', 'Traveling Wilburys', 'not-the-normalized-form'"
                            + ", 'SEED_LIST', 'SEED', now())"))
                    .as("#219: no longer rejected -- artist_owner_name_key, the only constraint that "
                            + "ever caught this shape, is gone")
                    .doesNotThrowAnyException();
        }

        try (Connection c = postgres.createConnection(""); Statement s = c.createStatement()) {
            // 6. The actual bug: two DIFFERENT owners with the same artist name must now both
            // succeed -- this is what the orphaned constraint was wrongly blocking in production.
            String mudcrutchNormalizedName = ArtistNameNormalizer.normalize("Mudcrutch");
            s.execute("INSERT INTO artist (owner, name, normalized_name, source, status, created_at) "
                    + "VALUES ('rob@example.com', 'Mudcrutch', '" + mudcrutchNormalizedName
                    + "', 'SEED_LIST', 'SEED', now())");
            s.execute("INSERT INTO artist (owner, name, normalized_name, source, status, created_at) "
                    + "VALUES ('david@example.com', 'Mudcrutch', '" + mudcrutchNormalizedName
                    + "', 'SEED_LIST', 'SEED', now())");

            ResultSet rs = s.executeQuery("SELECT count(*) FROM artist WHERE name = 'Mudcrutch'");
            rs.next();
            assertThat(rs.getInt(1)).as("both owners' Mudcrutch rows persisted").isEqualTo(2);

            // 7. No data loss: the pre-existing legacy row survived the whole migration chain.
            ResultSet legacyRow = s.executeQuery("SELECT count(*) FROM artist WHERE name = 'Nebraska'");
            legacyRow.next();
            assertThat(legacyRow.getInt(1)).as("pre-existing legacy row survives").isEqualTo(1);
        }
    }

    private static boolean constraintExists(Statement s, String constraintName) throws Exception {
        ResultSet rs = s.executeQuery(
                "SELECT count(*) FROM pg_constraint WHERE conrelid = 'artist'::regclass "
                        + "AND conname = '" + constraintName + "'");
        rs.next();
        return rs.getInt(1) == 1;
    }

    /** Column sets (comma-joined, sorted) of every UNIQUE constraint currently on {@code artist}. */
    private static List<String> uniqueConstraintColumnSets(Statement s) throws Exception {
        ResultSet rs = s.executeQuery("""
                SELECT string_agg(attr.attname, ',' ORDER BY attr.attname) AS cols
                FROM pg_constraint con
                JOIN pg_attribute attr ON attr.attrelid = con.conrelid AND attr.attnum = ANY (con.conkey)
                WHERE con.contype = 'u' AND con.conrelid = 'artist'::regclass
                GROUP BY con.oid
                """);
        List<String> result = new ArrayList<>();
        while (rs.next()) {
            result.add(rs.getString("cols"));
        }
        return result;
    }
}
