package com.robsartin.setlistscout.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Regression for the issue #44 prod crash. Production's tables predate multi-tenancy (#27): they
 * hold rows but have NO `owner` column, and V1's `CREATE TABLE IF NOT EXISTS` left them as-is when
 * Flyway adopted the DB (#30), so `ddl-auto=validate` crash-looped on the missing column.
 *
 * {@link MigrationAgainstPopulatedDbTest} missed this because it seeds the "populated" DB from V1
 * itself (which already has `owner`). This test builds a genuine LEGACY pre-owner schema -- no
 * `owner`, no ZIP-geocode lat/long, no band-site URL -- then asserts the migrations retrofit
 * `owner` (backfilled, NOT NULL) and the other columns the entities expect. Runs in CI (needs
 * Docker). Without V2 this fails: `owner` never gets added.
 */
@Testcontainers
class LegacyOwnerColumnMigrationTest {

    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    // The schema as it existed BEFORE the owner / ZIP-geocode / band-site columns were added.
    private static final String LEGACY_SCHEMA = """
            CREATE TABLE artist (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(255) NOT NULL,
                source varchar(255) NOT NULL,
                status varchar(255) NOT NULL,
                created_at timestamp(6) with time zone NOT NULL
            );
            CREATE TABLE search_settings (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                city varchar(255),
                state varchar(255),
                radius_miles integer NOT NULL,
                months_ahead integer NOT NULL
            );
            CREATE TABLE show_event (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                artist_name varchar(255) NOT NULL,
                event_date_time timestamp(6) without time zone NOT NULL,
                venue_name varchar(255) NOT NULL,
                source varchar(255) NOT NULL,
                discovered_at timestamp(6) with time zone NOT NULL
            );
            """;

    @Test
    void retrofitsOwnerColumnOntoLegacyPopulatedSchema() throws Exception {
        // 1. Stand up the legacy schema with a pre-existing row per table (no owner).
        try (Connection c = postgres.createConnection(""); Statement s = c.createStatement()) {
            s.execute(LEGACY_SCHEMA);
            s.execute("INSERT INTO artist (name, source, status, created_at) "
                    + "VALUES ('Dawes', 'SEED_LIST', 'SEED', now())");
            s.execute("INSERT INTO search_settings (city, state, radius_miles, months_ahead) "
                    + "VALUES ('Austin', 'TX', 50, 6)");
            s.execute("INSERT INTO show_event (artist_name, event_date_time, venue_name, source, discovered_at) "
                    + "VALUES ('Dawes', TIMESTAMP '2026-09-01 20:00:00', 'Moody', 'ticketmaster', now())");
        }

        // 2. Adopt Flyway with the app's real settings and migrate (V1 no-ops, V2 retrofits owner).
        MigrateResult result = Flyway.configure()
                .dataSource(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .locations("classpath:db/migration")
                .load()
                .migrate();
        assertThat(result.success).isTrue();

        // 3. Every table now has a NOT NULL `owner`, and the pre-existing rows were backfilled.
        try (Connection c = postgres.createConnection(""); Statement s = c.createStatement()) {
            for (String table : new String[]{"artist", "search_settings", "show_event"}) {
                ResultSet ownerCol = s.executeQuery(
                        "SELECT is_nullable FROM information_schema.columns "
                        + "WHERE table_name = '" + table + "' AND column_name = 'owner'");
                assertThat(ownerCol.next()).as("owner column exists on " + table).isTrue();
                assertThat(ownerCol.getString(1)).as("owner is NOT NULL on " + table).isEqualTo("NO");

                ResultSet backfilled = s.executeQuery(
                        "SELECT count(*) FROM " + table + " WHERE owner IS NOT NULL");
                backfilled.next();
                assertThat(backfilled.getInt(1)).as("legacy row backfilled in " + table).isEqualTo(1);
            }

            // A later feature column (added by V2's reconciliation) is present too -- proves the
            // migration doesn't stop at owner and leave the next missing column to crash prod.
            ResultSet latitude = s.executeQuery("SELECT count(*) FROM information_schema.columns "
                    + "WHERE table_name = 'search_settings' AND column_name = 'latitude'");
            latitude.next();
            assertThat(latitude.getInt(1)).as("latitude reconciled onto legacy search_settings").isEqualTo(1);
        }
    }
}
