-- Artist relationship graph storage layer (issue #109 phase 1, following the go/no-go recommendation
-- in docs/explorations/2026-08-14-artist-graph-model.md section 2). Records the actual relationship
-- assertion itself -- (from_artist) --[type]--> (to_artist), asserted by a specific RelationSource,
-- with its own note/weight/timestamp -- instead of the current one-hop, overwrite-on-conflict
-- breadcrumb columns on artist (discovered_via/source/note). The whole point: two different sources
-- corroborating the same (owner, from, to, type) relationship become two distinct edges, not a
-- silently-dropped second discovery (see artist_edge_unique below).
--
-- Column shape follows house style (V1's baseline, V6/V7's scan_job/expand_job): IDENTITY id,
-- varchar(255) for plain Strings, timestamp(6) with time zone for Instant. note is text (not
-- varchar(255)) per V9's D6 precedent -- provenance notes can be longer than 255 chars.
-- ddl-auto=validate is the ground truth this is checked against.
CREATE TABLE IF NOT EXISTS artist_edge (
    id             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner          varchar(255) NOT NULL,
    from_artist_id bigint NOT NULL,
    to_artist_id   bigint NOT NULL,
    type           varchar(255) NOT NULL,
    source         varchar(255) NOT NULL,
    note           text,
    weight         double precision,
    created_at     timestamp(6) with time zone NOT NULL,
    CONSTRAINT artist_edge_pkey PRIMARY KEY (id),
    CONSTRAINT artist_edge_from_fkey FOREIGN KEY (from_artist_id) REFERENCES artist(id),
    CONSTRAINT artist_edge_to_fkey   FOREIGN KEY (to_artist_id)   REFERENCES artist(id),
    CONSTRAINT artist_edge_unique UNIQUE (owner, from_artist_id, to_artist_id, type, source)
);

-- Supporting indexes for from/to lookups (traversal queries, "why is X in my candidates").
-- Not required by Hibernate's entity mapping, so ddl-auto=validate does not check for them --
-- purely for query performance, same as scan_job_next_due_at_idx / expand_job_next_due_at_idx.
CREATE INDEX IF NOT EXISTS artist_edge_from_idx ON artist_edge (owner, from_artist_id);
CREATE INDEX IF NOT EXISTS artist_edge_to_idx   ON artist_edge (owner, to_artist_id);
