-- Baseline schema for Setlist Scout, matching the Hibernate-mapped entities (see ADR-0009).
-- ddl-auto is 'validate', so schema changes ship as new V__ migrations, not ddl-auto guesswork.
--
-- IF NOT EXISTS + Flyway baseline-on-migrate lets this adopt cleanly on an already-populated
-- database (existing schema is left as-is and marked applied) as well as create a fresh one.

CREATE TABLE IF NOT EXISTS artist (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    source varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    discovered_via varchar(255),
    note varchar(255),
    official_site_url varchar(255),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT artist_pkey PRIMARY KEY (id),
    CONSTRAINT artist_owner_name_key UNIQUE (owner, name),
    CONSTRAINT artist_source_check CHECK (source IN ('SEED_LIST', 'MEMBER_EXPANSION', 'SIMILAR_EXPANSION', 'TRIBUTE_EXPANSION')),
    CONSTRAINT artist_status_check CHECK (status IN ('SEED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS search_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner varchar(255) NOT NULL,
    postal_code varchar(255),
    city varchar(255),
    state varchar(255),
    latitude double precision,
    longitude double precision,
    radius_miles integer NOT NULL,
    months_ahead integer NOT NULL,
    CONSTRAINT search_settings_pkey PRIMARY KEY (id),
    CONSTRAINT search_settings_owner_key UNIQUE (owner)
);

CREATE TABLE IF NOT EXISTS show_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner varchar(255) NOT NULL,
    artist_name varchar(255) NOT NULL,
    event_date_time timestamp(6) without time zone NOT NULL,
    venue_name varchar(255) NOT NULL,
    venue_city varchar(255),
    price numeric(38, 2),
    source varchar(255) NOT NULL,
    ticket_url varchar(255),
    discovered_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT show_event_pkey PRIMARY KEY (id),
    CONSTRAINT show_event_owner_artist_name_event_date_time_venue_name_key UNIQUE (owner, artist_name, event_date_time, venue_name)
);
