-- Issue #286 (Films 2/3). The person -> work half of the film bridge: what a person made, so that
-- 3/3 can say "Goodfellas -- because you follow Scorsese" about a screening 1/3 already stores.
--
-- Three things, and none of them belong on the tables that exist. A work is not a performer:
-- artist_edge FK-constrains BOTH endpoints to artist(id), and artist's identity is
-- UNIQUE (owner, normalized_name), which cannot tell Dune (1984) from Dune (2021). Putting films in
-- artist would also feed them to the review queue, the scan claim and the expansion sources --
-- exactly the pollution V38's cinema suppression exists to prevent.
--
-- Column shape follows V10's artist_edge: IDENTITY id, varchar(255) for plain Strings,
-- timestamp(6) with time zone for Instant. ddl-auto=validate is the ground truth.

-- work -- a film, for now. Named for the ontology rather than for film, because a work is the
-- general shape (segue's NodeKind: PERSON, GROUP, WORK, PLACE, EVENT, CONCEPT) and a role is an
-- edge, never a node type. Nothing here is film-specific.
--
-- IDENTITY IS THE QID, not title+year. #284 assumed title+year, and validating the Wikidata path
-- falsified it: P577 (publication date) is multi-valued -- one statement per country release -- so
-- 38 of Martin Scorsese's 112 films come back with more than one year and 4 with none. Keyed on
-- title+year, a third of films would get two rows. Keyed on the QID they get one, and title+year
-- becomes what it actually is: the key a screening is MATCHED on, which is 3/3's problem.
--
-- release_year is therefore nullable and is MIN(P577), the original release. Nullable because
-- Wikidata states no year for 4 of those 112, and a film with no year is still a film; dropping it
-- would be the parser-drops-what-it-cannot-parse failure in a new place.
CREATE TABLE IF NOT EXISTS work (
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner            varchar(255) NOT NULL,
    wikidata_qid     varchar(255) NOT NULL,
    title            varchar(255) NOT NULL,
    normalized_title varchar(255) NOT NULL,
    release_year     integer,
    created_at       timestamp(6) with time zone NOT NULL,
    CONSTRAINT work_pkey PRIMARY KEY (id),
    CONSTRAINT work_unique UNIQUE (owner, wikidata_qid)
);

-- The match key 3/3 will join a screening on: show_event carries a normalized title and a year,
-- never a QID, because a cinema calendar has no idea what Wikidata is. Indexed now because it is
-- free now and because an index added later is an index nobody remembers is load-bearing.
CREATE INDEX IF NOT EXISTS work_match_idx ON work (owner, normalized_title, release_year);

-- person_work_edge -- (artist) --[role]--> (work), as asserted by one source.
--
-- role is a plain varchar, not an enum, for V10's reason: the valid set is defined by whichever
-- sources exist, not by a fixed list on the table. The four Wikidata can emit today (DIRECTED,
-- ACTED_IN, WROTE_SCREENPLAY_FOR, PRODUCED) are segue's edge-type spellings, deliberately, so the
-- two graphs can be read together later without a translation layer.
--
-- Unique on all five columns INCLUDING source, so a second source asserting the same role is a
-- second corroborating edge rather than a DataIntegrityViolationException -- the model-level fix
-- V10 made for silent corroboration loss, applied here rather than rediscovered later.
CREATE TABLE IF NOT EXISTS person_work_edge (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner      varchar(255) NOT NULL,
    artist_id  bigint NOT NULL,
    work_id    bigint NOT NULL,
    role       varchar(255) NOT NULL,
    source     varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT person_work_edge_pkey PRIMARY KEY (id),
    CONSTRAINT person_work_edge_artist_fkey FOREIGN KEY (artist_id) REFERENCES artist(id),
    CONSTRAINT person_work_edge_work_fkey FOREIGN KEY (work_id) REFERENCES work(id),
    CONSTRAINT person_work_edge_unique UNIQUE (owner, artist_id, work_id, role, source)
);

CREATE INDEX IF NOT EXISTS person_work_edge_artist_idx ON person_work_edge (owner, artist_id);
CREATE INDEX IF NOT EXISTS person_work_edge_work_idx ON person_work_edge (owner, work_id);

-- artist.wikidata_* -- which Wikidata entity this artist IS, once something has resolved it.
--
-- Nullable, and deliberately so: most artists are never resolved, and the ones whose names are
-- ambiguous must stay unresolved rather than be guessed. Live Wikidata matches "Willie Nelson" to
-- the musician AND an American boxer, and "Nirvana" to three different bands -- a wrong QID here
-- is well-formed, resolves cleanly, and silently attaches somebody else's filmography, which is
-- the one error no later step can detect.
--
-- The label and description are stored alongside the QID for exactly that reason: they are what a
-- human reads on the artist page to see that Q206112 is the country musician and not the boxer.
-- Without them a wrong match is a number nobody can check.
ALTER TABLE artist ADD COLUMN IF NOT EXISTS wikidata_qid varchar(255);
ALTER TABLE artist ADD COLUMN IF NOT EXISTS wikidata_label varchar(255);
ALTER TABLE artist ADD COLUMN IF NOT EXISTS wikidata_description varchar(255);
