-- Reconcile the `id` column's auto-generation on an adopted legacy database (issue #53).
--
-- The entities use @GeneratedValue(IDENTITY), which needs each table's `id` to be a
-- GENERATED ... AS IDENTITY column. In the adopted prod DB, artist/show_event had it but
-- search_settings did not (its id was a plain bigint with no default), so every new user's
-- first-visit SearchSettings insert sent a null id and failed with a NOT NULL violation.
-- Same drift family as V2: V1's `CREATE TABLE IF NOT EXISTS` couldn't fix a pre-existing table.
--
-- For each table, if `id` is not already an identity column, add BY DEFAULT identity and seed
-- the backing sequence past the current max so it never collides with an existing row. Idempotent:
-- a no-op on a fresh DB (V1 already made these identity) and where a prior manual fix added it.

DO $$
DECLARE
    tbl text;
BEGIN
    FOREACH tbl IN ARRAY ARRAY['artist', 'search_settings', 'show_event'] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'id' AND is_identity = 'YES'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', tbl);
            EXECUTE format(
                'SELECT setval(pg_get_serial_sequence(%L, ''id''), GREATEST((SELECT max(id) FROM %I), 1))',
                tbl, tbl);
        END IF;
    END LOOP;
END $$;
