-- Durable scan-job queue (Phase B PR3b, issue #86): one row per (owner, artist_id, source)
-- ShowSource check. Populated by scan.ScanJobListener from ArtistActivated/ArtistDeactivated/
-- SettingsChanged; inert until the paced poller (PR4) starts draining SCHEDULED jobs.
--
-- Column shape mirrors scan.ScanJob's Hibernate mapping directly (house style set by V1's
-- baseline for artist/show_event: IDENTITY id per V3's reconciliation, varchar(255) for plain
-- Strings, timestamp(6) with time zone for Instant -- see event_publication's V4 for that
-- Instant precedent). ddl-auto=validate is the ground truth this is checked against.
CREATE TABLE IF NOT EXISTS scan_job (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner                 varchar(255) NOT NULL,
    artist_id             bigint NOT NULL,
    source                varchar(255) NOT NULL,
    status                varchar(255) NOT NULL,
    attempts              integer NOT NULL,
    last_error            varchar(255),
    last_run_at           timestamp(6) with time zone,
    next_due_at           timestamp(6) with time zone NOT NULL,
    claimed_at            timestamp(6) with time zone,
    location_fingerprint  varchar(255),
    CONSTRAINT scan_job_pkey PRIMARY KEY (id),
    CONSTRAINT scan_job_owner_artist_id_source_key UNIQUE (owner, artist_id, source),
    CONSTRAINT scan_job_status_check CHECK (status IN ('SCHEDULED', 'RUNNING', 'FAILED'))
);

-- Supporting index for the paced poller's due-job scan (PR4); not required by Hibernate's
-- entity mapping, so ddl-auto=validate does not check for it -- purely for query performance.
CREATE INDEX IF NOT EXISTS scan_job_next_due_at_idx ON scan_job (next_due_at);
