-- Durable expand-job queue (Phase B PR3b, issue #86): one row per (owner, artist_id, source)
-- relation-source check. Populated by expansion.ExpandJobListener from ArtistActivated/
-- ArtistDeactivated; inert until the paced poller (PR4) starts draining SCHEDULED jobs.
--
-- Column shape mirrors expansion.ExpandJob's Hibernate mapping directly, following the same
-- house style as V6's scan_job (IDENTITY id, varchar(255) for plain Strings, timestamp(6) with
-- time zone for Instant) minus the location_fingerprint column -- expansion isn't location-scoped.
-- ddl-auto=validate is the ground truth this is checked against.
CREATE TABLE IF NOT EXISTS expand_job (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner                 varchar(255) NOT NULL,
    artist_id             bigint NOT NULL,
    source                varchar(255) NOT NULL,
    status                varchar(255) NOT NULL,
    attempts              integer NOT NULL,
    last_error            varchar(255),
    last_run_at           timestamp(6) with time zone,
    next_due_at           timestamp(6) with time zone NOT NULL,
    claimed_at            timestamp(6) with time zone,
    CONSTRAINT expand_job_pkey PRIMARY KEY (id),
    CONSTRAINT expand_job_owner_artist_id_source_key UNIQUE (owner, artist_id, source),
    CONSTRAINT expand_job_status_check CHECK (status IN ('SCHEDULED', 'RUNNING', 'FAILED'))
);

-- Supporting index for the paced poller's due-job scan (PR4); not required by Hibernate's
-- entity mapping, so ddl-auto=validate does not check for it -- purely for query performance.
CREATE INDEX IF NOT EXISTS expand_job_next_due_at_idx ON expand_job (next_due_at);
